### ISSUE TITLE
Patch --version to show commit id

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/qemu#2]
We should consider patching the output of `--version` to show the commit id and maybe also the default machine type to make debugging issues easier (as we do for the other system components).

**Comment by jodh-intel** [comment]
Once we have this, we can add the version string to the `cc-runtime cc-env` output (which currently shows all component versions except the hypervisor the runtime has been configured to use).

**Comment by grahamwhaley** [comment]
There appears to be .git versioning support in the Makefile already - but it is not clear to me on how to enable it:
https://git.qemu.org/?p=qemu.git;a=blob;f=Makefile;h=81447b1f08656972dd83647e992c607ceb63a2cd;hb=HEAD#l295
/cc @anthonyzxu

**Comment by jodh-intel** [comment]
This may no longer be required - see https://github.com/clearcontainers/packaging/issues/100.

**Comment by gorozco1** [comment]
@jodh-intel we are doing that in: https://github.com/clearcontainers/packaging/pull/99

**Comment by jodh-intel** [comment]
Closing as problem solved.
